name: Docker Image CI

on:
  workflow_dispatch:

env:
  TARGET_PYTHON_BASEURL:     https://www.python.org/ftp/python/
  TARGET_PYTHON_GET_PIP_URL: https://bootstrap.pypa.io/get-pip.py
  TARGET_PYTHON_PIP_VERSION: 24.3.1

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        TARGET_WINDOWS_VERSION:
        - ltsc2025
        - ltsc2022
        - ltsc2019
        - 20H2
        - 2009
        - 2004
        - 1909
        - 1903
        - 1809
        - 1803
        - 1709
        TARGET_PYTHON_VERSION:
        - 3.13.1
        - 3.12.8
        - 3.11.9
        - 3.10.11
        - 3.9.13
        - 3.8.10
        - 3.7.8
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: >
        docker build
        -t ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}-${{ matrix.TARGET_WINDOWS_VERSION }}
        -t ghcr.io/${{ github.repository_owner }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}-${{ matrix.TARGET_WINDOWS_VERSION }}
        -t ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')-${{ matrix.TARGET_WINDOWS_VERSION }}
        -t ghcr.io/${{ github.repository_owner }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')-${{ matrix.TARGET_WINDOWS_VERSION }}
        --build-arg WINDOWS_VERSION=${{ matrix.TARGET_WINDOWS_VERSION }}
        --build-arg PYTHON_VERSION=${{ matrix.TARGET_PYTHON_VERSION }}
        --build-arg PYTHON_RELEASE=${{ matrix.TARGET_PYTHON_VERSION }}
        --build-arg PYTHON_PIP_VERSION=${{ env.TARGET_PYTHON_PIP_VERSION }}
        --build-arg PYTHON_GET_PIP_URL=${{ env.TARGET_PYTHON_GET_PIP_URL }}
        .

    - name: Tag latest
      if: ${{ strategy.job-index == 0}}
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}-${{ matrix.TARGET_WINDOWS_VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver
        docker tag ghcr.io/${{ github.repository_owner }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}-${{ matrix.TARGET_WINDOWS_VERSION }} ghcr.io/${{ github.repository_owner }}/python-nanoserver
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')-${{ matrix.TARGET_WINDOWS_VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver
        docker tag ghcr.io/${{ github.repository_owner }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')-${{ matrix.TARGET_WINDOWS_VERSION }} ghcr.io/${{ github.repository_owner }}/python-nanoserver


    - name: Tag ltsc2025
      if: ${{ matrix.TARGET_WINDOWS_VERSION == 2025}}
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}-${{ matrix.TARGET_WINDOWS_VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}
        docker tag ghcr.io/${{ github.repository_owner }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}-${{ matrix.TARGET_WINDOWS_VERSION }} ghcr.io/${{ github.repository_owner }}/python-nanoserver:${{ matrix.TARGET_PYTHON_VERSION }}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')-${{ matrix.TARGET_WINDOWS_VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')
        docker tag ghcr.io/${{ github.repository_owner }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')-${{ matrix.TARGET_WINDOWS_VERSION }} ghcr.io/${{ github.repository_owner }}/python-nanoserver:$("${{ matrix.TARGET_PYTHON_VERSION }}" -replace '\.\d+$', '')

    - name: push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-nanoserver --all-tags
        docker push ghcr.io/${{ github.repository_owner }}/python-nanoserver --all-tags
